version : '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-95=n41&^z0w=qq=pcf@pnkka$=$g#it0^)go9e2ac!36q@n)r3
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
  redis: 
    image: "redis:alpine"
    ports:
      - "6379:6379"
  celery:
    build: .
    command: celery -A django_carsharing worker -l info
    volumes:
      - ./:/usr/src/app/
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-95=n41&^z0w=qq=pcf@pnkka$=$g#it0^)go9e2ac!36q@n)r3
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - redis
  flower:
    image: mher/flower 
    container_name: flower
    command: celery flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=8888
    ports:
      - 8888:8888 
  celery-beat:
    build: .
    command: celery -A django_carsharing beat -l info
    volumes:
      - ./:/usr/src/app/
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-95=n41&^z0w=qq=pcf@pnkka$=$g#it0^)go9e2ac!36q@n)r3
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - redis
  smtp-server:
    image: mailhog/mailhog
    expose:
      - 1025
      - 8025
    ports:
      - '1025:1025'
      - '8025:8025'
