# Generated by Django 4.2.6 on 2023-10-18 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название города"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("make", models.CharField(max_length=50, verbose_name="Марка")),
                ("model", models.CharField(max_length=50, verbose_name="Модель")),
                ("year", models.PositiveIntegerField(verbose_name="Год выпуска")),
                (
                    "registration_number",
                    models.CharField(
                        max_length=20, verbose_name="Регистрационный номер"
                    ),
                ),
                ("color", models.CharField(max_length=30, verbose_name="Цвет")),
                ("range", models.PositiveIntegerField(verbose_name="Запас хода")),
                (
                    "is_available",
                    models.BooleanField(
                        default=True, verbose_name="Доступен для аренды"
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="carsharing.city",
                        verbose_name="Город",
                    ),
                ),
            ],
        ),
    ]
